apiVersion: projectriff.io/v1
kind: Topic
metadata:
  name: blog-webhook
  namespace: blog
---
apiVersion: projectriff.io/v1
kind: Function
metadata:
  name: blog-updater
  namespace: blog
spec:
  protocol: http
  input: blog-webhook
  container:
    image: asia.gcr.io/fe-tmaki/blog-updater:latest
    env:
    - name: BLOG_UPDATER_GITHUB_TOKEN_MAKING_BLOG_IK_AM
      valueFrom:
        secretKeyRef:
          name: blog-updater-secret
          key: blog-updater-github-token
    - name: BLOG_UPDATER_GITHUB_TOKEN_UTMAKI_BLOG_IK_AM
      valueFrom:
        secretKeyRef:
          name: blog-updater-secret
          key: blog-updater-github-token
    - name: SPRING_DATASOURCE_URL
      valueFrom:
        secretKeyRef:
          name: blog-db-secret
          key: mysql-jdbc-url
    - name: SPRING_DATASOURCE_USERNAME
      valueFrom:
        secretKeyRef:
          name: blog-db-secret
          key: mysql-user
    - name: SPRING_DATASOURCE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: blog-db-secret
          key: mysql-password