kind: Service
apiVersion: v1
metadata:
  name: blog-updater-service
  labels:
    app: blog-updater
spec:
  selector:
    app: blog-updater
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30091
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blog-updater-deployment
  labels:
    app: blog-updater
spec:
  replicas: 1
  revisionHistoryLimit: 4
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: blog-updater
      annotations:
        kubernetes.io/change-cause: "FIXME"
    spec:
      containers:
      - name: blog-updater
        image: asia.gcr.io/fe-tmaki/blog-updater:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_PROFILES_ACTIVE
          value: cloud,kubernetes
        - name: JAVA_OPTS
          value: "-Xmx285M -Xss1M -XX:MaxMetaspaceSize=113M -XX:ReservedCodeCacheSize=32M -XX:CompressedClassSpaceSize=20M -XX:MaxDirectMemorySize=32M -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1"
        - name: SECURITY_USER_NAME
          valueFrom:
            configMapKeyRef:
              name: blog-config
              key: ops-username
        - name: SECURITY_USER_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: blog-config
              key: ops-password
        - name: blog-updater.github-token.making/blog.ik.am
          valueFrom:
            configMapKeyRef:
              name: blog-updater-config
              key: blog-updater-github-token
        - name: blog-updater.github-token.utmaki/blog.ik.am
          valueFrom:
            configMapKeyRef:
              name: blog-updater-config
              key: blog-updater-github-token
        - name: VCAP_APPLICATION
          valueFrom:
            configMapKeyRef:
              name: blog-updater-config
              key: vcap-application.json
        - name: VCAP_SERVICES
          valueFrom:
            configMapKeyRef:
              name: blog-updater-config
              key: vcap-services.json
        resources:
          limits:
            memory: "512Mi"
          requests:
            memory: "512Mi"
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 180
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 3
